# Generated by Django 5.0.4 on 2024-04-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_userdata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
